package advent.of.code

suspend fun main(args: Array<String>) {
    var start = System.currentTimeMillis()
//    println("day1 - part1 - ${advent.of.code.day01.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day1 - part2 - ${advent.of.code.day01.part2()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day2 - part1 - ${advent.of.code.day02.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day2 - part2 - ${advent.of.code.day02.part2()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day3 - part1 - ${advent.of.code.day03.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day3 - part2 - ${advent.of.code.day03.part2()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day4 - part1 - ${advent.of.code.day04.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day4 - part2 - ${advent.of.code.day04.part2()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day5 - part1 - ${advent.of.code.day05.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day5 - part2 - ${advent.of.code.day05.part2()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day6 - part1 - ${advent.of.code.day06.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day6 - part2 - ${advent.of.code.day06.part2()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day7 - part1 - ${advent.of.code.day07.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day7 - part2 - ${advent.of.code.day07.part2()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day8 - part1 - ${advent.of.code.day08.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day8 - part2 - ${advent.of.code.day08.part2()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day9 - part1 - ${advent.of.code.day09.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day9 - part2 - ${advent.of.code.day09.part2()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day10 - part1 and part2 - ${advent.of.code.day10.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day11 - part1 - ${advent.of.code.day11.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day11 - part2 - ${advent.of.code.day11.part2()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day12 - part1 - ${advent.of.code.day12.part1()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
//    println("day12 - part2 - ${advent.of.code.day12.part2()} - ${System.currentTimeMillis() - start}ms")
//    start = System.currentTimeMillis()
    println("day13 - part1 - ${advent.of.code.day13.part1()} - ${System.currentTimeMillis() - start}ms")
    start = System.currentTimeMillis()
    println("day13 - part2 - ${advent.of.code.day13.part2()} - ${System.currentTimeMillis() - start}ms")
}